version: '1.0'

services:
  app:
    image: 'nikitamakoveev/internal-comms2:latest'
    container_name: internal-comms
    depends_on:
      - db
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        PGDATA: /var/lib/postgresql/data/pgdata
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres